wallpaper {
  monitor =
  # Create a symlink using "ln -sf 'target_wallpaper.jpg' ~/.config/hypr/current_wallpaper.jpg" the target wallpaper can be either png or jpg, it doesn't matter.
  path = ~/.config/hypr/current_wallpaper.jpg
  fit_mode = cover
}
